apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-01-30T20:08:36Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
  resourceVersion: "8218"
  selfLink: /api/v1/namespaces/default/services/hello-world-rest-api
  uid: 11e6c5db-07f5-42e6-a654-b1f76b39e083
spec:
  clusterIP: 10.72.2.222
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30214
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.239.74.232
